import type { Product } from './products';

export const PRODUCTS_PART_3: ReadonlyArray<Product> = [
  {
    slug: 'serviettes-lin-pablo',
    name: 'Serviettes en lin Pablo',
    brand: 'Tissage Xérès',
    category: 'Textile',
    shortDescription: 'Lin lavé, 50×50, lot de 4.',
    description: "Lot de 4 serviettes de table en lin lavé, qui absorbent bien et sèchent vite. Le tissage à plat donne un tombé impeccable.",
    priceCents: 4900,
    compareAtCents: 5900,
    currency: 'EUR',
    badge: 'promo',
    image: '/images/products/serviettes-pablo.webp',
    alt: 'Serviettes en lin lavé pliées sur une table',
    gallery: [{ url: '/images/products/serviettes-pablo.webp', alt: 'Serviettes Pablo' }],
    variants: [
      { id: 'pablo-naturel', label: 'Naturel', priceCents: 4900, options: [{ label: 'Teinte', value: 'Naturel', swatch: '#EFE7D6' }], stock: 26 },
      { id: 'pablo-tc', label: 'Terracotta', priceCents: 4900, options: [{ label: 'Teinte', value: 'Terracotta', swatch: '#C04A2A' }], stock: 12 },
    ],
    materials: ['Lin lavé européen'],
    care: ['Lavage 40°', 'Pas de sèche-linge'],
    weightGrams: 380,
    freeShippingEligible: true,
  },
  {
    slug: 'lampe-poser-elma',
    name: 'Lampe à poser Elma',
    brand: 'Tala Studio',
    category: 'Luminaire',
    shortDescription: 'Lampe de chevet en grès, abat-jour en lin.',
    description: "Une lampe de chevet douce et chaude, parfaite en bout de canapé ou sur une table de nuit. Le pied en grès lourd assure une stabilité sans faille.",
    priceCents: 12900,
    currency: 'EUR',
    badge: 'new',
    image: '/images/products/lampe-elma.webp',
    alt: 'Lampe à poser avec pied en grès et abat-jour en lin',
    gallery: [{ url: '/images/products/lampe-elma.webp', alt: 'Lampe Elma' }],
    variants: [
      { id: 'elma-blanc', label: 'Grès blanc', priceCents: 12900, options: [{ label: 'Couleur', value: 'Blanc', swatch: '#E5E0D6' }], stock: 7 },
      { id: 'elma-noir', label: 'Grès noir', priceCents: 12900, options: [{ label: 'Couleur', value: 'Noir', swatch: '#27272A' }], stock: 5 },
    ],
    materials: ['Grès', 'Lin lavé'],
    care: ['Dépoussiérer à sec', 'Ampoule E14 remplaçable'],
    weightGrams: 1800,
    freeShippingEligible: true,
  },
  {
    slug: 'sel-poivre-noir',
    name: 'Moulin à poivre Casa',
    brand: 'Atelier Lorca',
    category: 'Arts de la table',
    shortDescription: 'Bois de noyer, mécanisme en céramique.',
    description: "Un moulin à poivre haut et élégant, taillé dans un seul bloc de noyer. Le mécanisme en céramique est garanti à vie.",
    priceCents: 6900,
    currency: 'EUR',
    image: '/images/products/moulin-casa.webp',
    alt: 'Moulin à poivre en noyer foncé',
    gallery: [{ url: '/images/products/moulin-casa.webp', alt: 'Moulin Casa' }],
    variants: [
      { id: 'casa-classique', label: 'Classique 20 cm', priceCents: 6900, options: [{ label: 'Taille', value: '20 cm' }], stock: 18 },
    ],
    materials: ['Noyer français', 'Mécanisme céramique'],
    care: ["Essuyer avec un chiffon sec", "Ne pas immerger le mécanisme"],
    weightGrams: 480,
    freeShippingEligible: true,
  },
  {
    slug: 'cintre-noyer-elli',
    name: 'Cintre en noyer Elli',
    brand: 'Elli',
    category: 'Art de vivre',
    shortDescription: 'Noyer huilé, forme cintrée.',
    description: "Un cintre en noyer massif, taillé pour respecter l'épaule des manteaux. Lot de 2.",
    priceCents: 3900,
    currency: 'EUR',
    image: '/images/products/cintre-elli.webp',
    alt: "Cintre en noyer à la forme cintrée",
    gallery: [{ url: '/images/products/cintre-elli.webp', alt: 'Cintre Elli' }],
    variants: [
      { id: 'elli-lot2', label: 'Lot de 2', priceCents: 3900, options: [{ label: 'Format', value: 'Lot de 2' }], stock: 24 },
    ],
    materials: ['Noyer français', 'Huile de lin'],
    care: ['Chiffon sec'],
    weightGrams: 280,
    freeShippingEligible: true,
  },
  {
    slug: 'theiere-email-yesi',
    name: 'Théière émaillée Yesi',
    brand: 'Malo Céramique',
    category: 'Arts de la table',
    shortDescription: 'Grès émaillé, infuseur inox, bec courbé.',
    description: "Une théière de 0,8 L avec infuseur inox intégré et bec courbé pour servir sans goutte.",
    priceCents: 5900,
    currency: 'EUR',
    badge: 'new',
    image: '/images/products/theiere-yesi.webp',
    alt: 'Théière en grès émaillé avec infuseur inox',
    gallery: [{ url: '/images/products/theiere-yesi.webp', alt: 'Théière Yesi' }],
    variants: [
      { id: 'yesi-craie', label: 'Craie', priceCents: 5900, options: [{ label: 'Couleur', value: 'Craie', swatch: '#E5E0D6' }], stock: 16 },
      { id: 'yesi-rust', label: 'Rouille', priceCents: 5900, options: [{ label: 'Couleur', value: 'Rouille', swatch: '#A24B1F' }], stock: 11 },
    ],
    materials: ['Grès émaillé', 'Infuseur inox'],
    care: ['Lavage main', 'Compatible théière sur feu doux'],
    weightGrams: 980,
    freeShippingEligible: true,
  },
];
