import type { Product } from './products';

export const PRODUCTS_PART_2: ReadonlyArray<Product> = [
  {
    slug: 'lampadaire-tala-led',
    name: 'Lampadaire Tala LED',
    brand: 'Tala Studio',
    category: 'Luminaire',
    shortDescription: 'Lampadaire en chêne clair, abat-jour en lin écru.',
    description: "Un lampadaire qui ne fait pas de bruit. Le piétement en chêne certifié FSC est tourné en Bourgogne, l'abat-jour en lin lavé est cousu à Roubaix. L'ampoule LED dimmable est remplaçable.",
    priceCents: 19900,
    currency: 'EUR',
    badge: 'new',
    image: '/images/products/lampe-tala.webp',
    alt: 'Lampadaire en chêne clair avec abat-jour en lin écru',
    gallery: [{ url: '/images/products/lampe-tala.webp', alt: 'Lampadaire Tala' }],
    variants: [
      { id: 'tala-naturel', label: 'Chêne naturel', priceCents: 19900, options: [{ label: 'Bois', value: 'Naturel', swatch: '#D4B895' }], stock: 6 },
      { id: 'tala-fume', label: 'Chêne fumé', priceCents: 21900, options: [{ label: 'Bois', value: 'Fumé', swatch: '#7A5C3F' }], stock: 4 },
    ],
    materials: ['Chêne FSC', 'Lin lavé', 'LED 12W dimmable'],
    care: ['Dépoussiérer à sec', 'Ampoule E27 remplaçable'],
    weightGrams: 4800,
    freeShippingEligible: false,
  },
  {
    slug: 'plaid-laine-brumaire',
    name: 'Plaid laine Brumaire',
    brand: 'Filature Brumaire',
    category: 'Textile',
    shortDescription: "Laine teinte en dégradé d'ocre, tissée en Roumanie.",
    description: "Tissé à partir de laine vierge issue d'élevages transylvains, ce plaid teint en dégradé d'ocre tient chaud sans étouffer.",
    priceCents: 11900,
    currency: 'EUR',
    image: '/images/products/plaid-brumaire.webp',
    alt: "Plaid en laine teinte en dégradé d'ocre roulé sur une chaise",
    gallery: [{ url: '/images/products/plaid-brumaire.webp', alt: 'Plaid Brumaire' }],
    variants: [
      { id: 'brumaire-ocre', label: 'Ocre', priceCents: 11900, options: [{ label: 'Teinte', value: 'Ocre', swatch: '#B17A2E' }], stock: 9 },
      { id: 'brumaire-ardoise', label: 'Ardoise', priceCents: 11900, options: [{ label: 'Teinte', value: 'Ardoise', swatch: '#4A5159' }], stock: 11 },
    ],
    materials: ['Laine vierge 100 %', 'Teintures naturelles'],
    care: ['Lavage à froid', 'Séchage à plat'],
    weightGrams: 1600,
    freeShippingEligible: true,
  },
  {
    slug: 'coussin-lin-ilde',
    name: 'Coussin en lin Ildé',
    brand: 'Ildé',
    category: 'Textile',
    shortDescription: 'Lin lavé écru, garnissage plumes, 45×45.',
    description: "Une housse de coussin douce au toucher, garnie de plumes certifiées. La fermeture invisible est cousue main.",
    priceCents: 7900,
    currency: 'EUR',
    image: '/images/products/coussin-ilde.webp',
    alt: 'Coussin en lin lavé écru de 45×45 cm',
    gallery: [{ url: '/images/products/coussin-ilde.webp', alt: 'Coussin Ildé' }],
    variants: [
      { id: 'ilde-ecru', label: 'Écru', priceCents: 7900, options: [{ label: 'Couleur', value: 'Écru', swatch: '#EFE7D6' }], stock: 14 },
      { id: 'ilde-tabac', label: 'Tabac', priceCents: 7900, options: [{ label: 'Couleur', value: 'Tabac', swatch: '#8A5A3B' }], stock: 9 },
    ],
    materials: ['Lin lavé', 'Plumes certifiées'],
    care: ['Housse lavable machine 30°', 'Garnissage non lavable'],
    weightGrams: 540,
    freeShippingEligible: true,
  },
];
