import type { Product } from './products';

export const PRODUCTS_PART_1: ReadonlyArray<Product> = [
  {
    slug: 'bouilloire-en-fonte-segura',
    name: 'Bouilloire en fonte Segura',
    brand: 'Maison Segura',
    category: 'Arts de la table',
    shortDescription: 'Fonte noire patinée à la main, bec verseur précis.',
    description: "Notre bouilloire Segura est coulée dans une fonderie familiale portugaise. Chaque pièce reçoit une patine noire appliquée à la main qui se bonifie avec l'usage.",
    priceCents: 8900,
    compareAtCents: 10900,
    currency: 'EUR',
    badge: 'promo',
    image: '/images/products/bouilloire-segura.webp',
    alt: 'Bouilloire en fonte noire à bec verseur posée sur un plan de travail',
    gallery: [{ url: '/images/products/bouilloire-segura.webp', alt: 'Bouilloire Segura vue 3/4' }],
    variants: [
      { id: 'segura-0-8l', label: '0,8 L', priceCents: 8900, options: [{ label: 'Contenance', value: '0,8 L' }], stock: 12 },
      { id: 'segura-1-2l', label: '1,2 L', priceCents: 11900, compareAtCents: 13900, options: [{ label: 'Contenance', value: '1,2 L' }], stock: 8 },
    ],
    materials: ['Fonte recyclée', "Patine à l'huile de lin"],
    care: ["Rincer à l'eau tiède", 'Sécher sur feu doux'],
    weightGrams: 1450,
    freeShippingEligible: true,
  },
  {
    slug: 'vase-terracotta-lorca',
    name: 'Vase Terracotta Lorca',
    brand: 'Atelier Lorca',
    category: 'Art de vivre',
    shortDescription: 'Céramique tournée à la main, formes organiques.',
    description: "Le vase Lorca est né d'une commande pour un fleuriste d'Amsterdam. Ses courbes douces mettent en valeur quelques branches d'eucalyptus ou une seule fleur de pivoine.",
    priceCents: 4900,
    currency: 'EUR',
    badge: 'new',
    image: '/images/products/vase-lorca.webp',
    alt: 'Vase en céramique terracotta aux formes organiques',
    gallery: [{ url: '/images/products/vase-lorca.webp', alt: 'Vase Lorca sur une table' }],
    variants: [
      { id: 'lorca-s', label: 'Petit (16 cm)', priceCents: 4900, options: [{ label: 'Taille', value: 'S' }], stock: 24 },
      { id: 'lorca-l', label: 'Grand (28 cm)', priceCents: 7900, options: [{ label: 'Taille', value: 'L' }], stock: 10 },
    ],
    materials: ["Argile de l'Aude", 'Email mat sans plomb'],
    care: ['Chiffon humide', 'Soucoupe recommandée'],
    weightGrams: 820,
    freeShippingEligible: true,
  },
  {
    slug: 'carafe-emaillee-vega',
    name: 'Carafe émaillée Vega',
    brand: 'Vega Céramique',
    category: 'Arts de la table',
    shortDescription: 'Grès émaillé vert sombre, bouchon en liège.',
    description: "Une carafe pour l'eau et les jus frais, taillée pour tenir au frigo et verser sans goutte. Le bouchon en liège naturel assure une étanchéité parfaite.",
    priceCents: 3400,
    compareAtCents: 3900,
    currency: 'EUR',
    badge: 'promo',
    image: '/images/products/carafe-vega.webp',
    alt: "Carafe en grès émaillé vert sombre avec bouchon en liège",
    gallery: [{ url: '/images/products/carafe-vega.webp', alt: 'Carafe Vega' }],
    variants: [
      { id: 'vega-vert', label: 'Vert sombre', priceCents: 3400, options: [{ label: 'Couleur', value: 'Vert', swatch: '#2C4034' }], stock: 18 },
      { id: 'vega-sable', label: 'Sable', priceCents: 3400, options: [{ label: 'Couleur', value: 'Sable', swatch: '#D4B895' }], stock: 14 },
    ],
    materials: ['Grès émaillé', 'Liège naturel'],
    care: ['Lave-vaisselle', 'Bouchon à la main'],
    weightGrams: 720,
    freeShippingEligible: true,
  },
  {
    slug: 'set-de-table-lin-xeres',
    name: 'Set de table en lin Xérès',
    brand: 'Tissage Xérès',
    category: 'Arts de la table',
    shortDescription: "Lin écru brodé d'un fin liseré terracotta.",
    description: "Tissé dans le nord de la France, ce set de table en lin lavé se froisse avec élégance.",
    priceCents: 2400,
    currency: 'EUR',
    badge: 'last',
    image: '/images/products/set-xeres.webp',
    alt: 'Set de table en lin écru brodé d\'un liseré terracotta',
    gallery: [{ url: '/images/products/set-xeres.webp', alt: 'Set de table Xérès' }],
    variants: [
      { id: 'xeres-tc', label: 'Terracotta', priceCents: 2400, options: [{ label: 'Liseré', value: 'Terracotta', swatch: '#C04A2A' }], stock: 3 },
      { id: 'xeres-noir', label: 'Noir', priceCents: 2400, options: [{ label: 'Liseré', value: 'Noir', swatch: '#18181B' }], stock: 22 },
    ],
    materials: ['Lin européen', 'Fil coton brodé main'],
    care: ['Lavage machine 30°', 'Repasser humide'],
    weightGrams: 180,
    freeShippingEligible: true,
  },
  {
    slug: 'mug-grese-malo',
    name: 'Mug en grès Malo',
    brand: 'Malo Céramique',
    category: 'Arts de la table',
    shortDescription: 'Grès noir, anse fine, email mat.',
    description: "Un mug sobre et généreux, parfait pour le café du matin et le chocolat du soir.",
    priceCents: 1900,
    currency: 'EUR',
    image: '/images/products/mug-malo.webp',
    alt: 'Mug en grès noir à anse fine',
    gallery: [{ url: '/images/products/mug-malo.webp', alt: 'Mug Malo' }],
    variants: [
      { id: 'malo-noir', label: 'Noir', priceCents: 1900, options: [{ label: 'Couleur', value: 'Noir', swatch: '#18181B' }], stock: 36 },
      { id: 'malo-sable', label: 'Sable', priceCents: 1900, options: [{ label: 'Couleur', value: 'Sable', swatch: '#D4B895' }], stock: 28 },
    ],
    materials: ['Grès', 'Email mat'],
    care: ['Lave-vaisselle', 'Micro-ondes'],
    weightGrams: 320,
    freeShippingEligible: true,
  },
  {
    slug: 'plateau-chene-noa',
    name: 'Plateau en chêne Noa',
    brand: 'Atelier Noa',
    category: 'Art de vivre',
    shortDescription: 'Chêne massif huilé, arêtes douces, fond creusé.',
    description: "Le plateau Noa accompagne les apéritifs et les petits-déjeuners.",
    priceCents: 5900,
    currency: 'EUR',
    badge: 'new',
    image: '/images/products/plateau-noa.webp',
    alt: 'Plateau rectangulaire en chêne massif',
    gallery: [{ url: '/images/products/plateau-noa.webp', alt: 'Plateau Noa' }],
    variants: [
      { id: 'noa-m', label: 'Moyen (40×25)', priceCents: 5900, options: [{ label: 'Taille', value: 'M' }], stock: 16 },
    ],
    materials: ['Chêne français', 'Huile de lin'],
    care: ['Chiffon humide', "Régaler à l'huile de lin tous les 6 mois"],
    weightGrams: 720,
    freeShippingEligible: true,
  },
  {
    slug: 'bougie-cire-vegetale-orin',
    name: 'Bougie cire végétale Orin',
    brand: 'Orin',
    category: 'Art de vivre',
    shortDescription: 'Cire de colza, parfum boisé, mèche coton.',
    description: "Une bougie propre, sans paraffine, qui ne dégage pas de suie.",
    priceCents: 3200,
    currency: 'EUR',
    badge: 'new',
    image: '/images/products/bougie-orin.webp',
    alt: 'Bougie dans un pot en verre fumé',
    gallery: [{ url: '/images/products/bougie-orin.webp', alt: 'Bougie Orin' }],
    variants: [
      { id: 'orin-bois', label: 'Bois fumé', priceCents: 3200, options: [{ label: 'Parfum', value: 'Bois fumé' }], stock: 22 },
      { id: 'orin-cedre', label: 'Cèdre', priceCents: 3200, options: [{ label: 'Parfum', value: 'Cèdre' }], stock: 18 },
    ],
    materials: ['Cire de colza', 'Mèche coton non blanchi'],
    care: ['Couper la mèche à 5 mm', 'Pas plus de 2 h'],
    weightGrams: 280,
    freeShippingEligible: true,
  },
];
